# Generated by Django 4.2.7 on 2025-07-29 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="A user-friendly name for the source, e.g., 'Example News Site'.", max_length=255)),
                ('url', models.URLField(help_text='The starting URL for the scraper.', max_length=2048, unique=True)),
                ('target_type', models.CharField(choices=[('BOTH', 'Both'), ('PDF', 'PDFs Only'), ('WEBSITE', 'Websites Only')], default='BOTH', help_text='Specify what content to scrape from this source.', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Only active sources will be used when the scraper is run.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
