# Generated by Django 4.2.7 on 2025-07-30 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('netloc', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('depth', models.IntegerField(default=0)),
                ('target', models.CharField(choices=[('BOTH', 'Both'), ('PDF', 'PDFs Only'), ('WEBSITE', 'Websites Only')], default='BOTH', help_text='Specify what type of content to scrape from this source.', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Only active sources will be used when the scraper is run.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sources',
                'unique_together': {('netloc', 'path')},
            },
        ),
    ]
