# Generated by Django 4.2.23 on 2025-07-27 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('netloc', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('depth', models.IntegerField(default=0)),
                ('target', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.ForeignKey(db_column='category_name', on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
            options={
                'unique_together': {('netloc', 'category')},
            },
        ),
    ]
