# Generated by Django 4.2.23 on 2025-07-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='netloc',
        ),
        migrations.RemoveField(
            model_name='article',
            name='path',
        ),
        migrations.AddField(
            model_name='article',
            name='drive_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
