# Generated by Django 4.2.23 on 2025-07-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('min_relevance_threshold', models.FloatField()),
                ('min_wordcount_threshold', models.IntegerField()),
            ],
        ),
    ]
