# Generated by Django 4.2.7 on 2025-07-29 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='min_wordcount_threshold',
        ),
    ]
