# Generated by Django 4.2.23 on 2025-07-27 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('articles', '0002_remove_article_netloc_remove_article_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance_score', models.FloatField()),
                ('article', models.ForeignKey(db_column='article_id', on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
                ('category', models.ForeignKey(db_column='category_name', on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
            options={
                'unique_together': {('article', 'category')},
            },
        ),
    ]
